site_name: Introdução do MarkDown

theme:
  name: material

nav :
 - index.md
 - enfase.md
 - paragrafo.md
 - titulo.md
 - blockquote.md
 - lista.md
 - links.md
 - imagens.md
 - codigo.md
 - lista-ordenada.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences